### ISSUE TITLE
Tracking text in Swedish (OS in FI)

### ISSUE THREAD

**Issue by Termitebug** [ZeiP/harbour-paketti#33]
Hi, I seem to have all tracking information (Posti+Matkahuolto) in Swedish despite my OS language being in Finnish. App's language is shown in Finnish. Can I remedy this via a config file or is this something in development end?

**Comment by ZeiP** [comment]
Which version are you using? I think there were some problems with the language detection that I fixed quite recently.

**Comment by Termitebug** [comment]
I'm using 0.8.1 version of Paketti.

**Comment by ZeiP** [comment]
Ok, and this is happening on all parcels, not just one? The language logic is defined in https://github.com/ZeiP/harbour-paketti/blob/master/qml/js/helpers.js#L64 , and for Posti it should use the languages in the order en, fi, sv, lt, lv. So if this happens to you with all packages it would seem most likely that there's something funny in your locale settings and Qt.locale().name is returning sv instead of fi.

It might be worthwhile to try changing the phone language first to some other (en/sv for example) and then back to fi. If that doesn't help I can provide you with an application version that has more debug output to help figure out what's wrong.

**Comment by Termitebug** [comment]
This is happening on all parcels, as you can see. So yeah, something funny in going on with my locale. I tried to change locales with no results. I'm running flashed image of SFOS 3.4.0.24 on Xperia XA2 H4493.

![Nayttokuva_paketti_edit](https://user-images.githubusercontent.com/11379204/106047289-183aff00-60ec-11eb-96f0-1d43b60eafbe.png)

**Comment by Termitebug** [comment]
So could you send me a debug version of the app? I will send you PM @-mail with my contact address.

**Comment by ZeiP** [comment]
You can download the debug version at https://filesender.ardcoras.fi/?s=download&token=691d08fc-bd6f-4a5b-9fc7-0cafccee0bf3 . It outputs some extra stuff to console. So basically if you install it and then launch the application in the command line (command is just ”harbour-paketti”), it should output a few lines on each update that would be helpful figuring out what's the problem.

**Comment by Termitebug** [comment]
Ah, okay. Thank you and sorry because I just send you an useless @-mail.

**Comment by ZeiP** [comment]
No worries! Let me know if the debug output shows that the locale is detected incorrectly, so I can try to fix any problems with it.

**Comment by Termitebug** [comment]
Okay the debug shows two following lines of my used locales. `[D] getlocale:68 - fi_FI` _and_ `[D] getLocale 96 - endLsv`.

**Comment by ZeiP** [comment]
Right, wasn't really hoping for that. There was a bug in the language detection code, it seems I didn't test the app properly in Finnish after changing it. Can you try this: https://filesender.ardcoras.fi/?s=download&token=53f5333c-64db-40c7-95e3-c3ba76f471af

**Comment by Termitebug** [comment]
Thank you, that did fix it. Now it is using only `fi_FI` locale. I will now close this issue.

**Comment by ZeiP** [comment]
Great, thanks. I'll re-open the issue to be fixed in the release version also.
